# Generated by Django 4.0.7 on 2022-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('cred', models.CharField(max_length=100)),
                ('cred_link', models.CharField(max_length=100)),
            ],
        ),
    ]
