# Generated by Django 4.0.7 on 2022-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='grade',
            field=models.FloatField(),
        ),
    ]
